### ISSUE TITLE
DTMF detection

### ISSUE THREAD

**Issue by qroft** [meyda/meyda#1176]
**Is your feature request related to a problem? Please describe.**
I am too dumb to join the Slack channel so i try it through here. I would love to know if it is possible to find out DTMF tones with Meyda.

**Describe the solution you'd like**
I have an idea for a new project where I need to recognise DTMF tones. So it would be awesome to get those from a Wegstrecke or uploaded mp3 file.

**Describe alternatives you've considered**
None yet. I found other libraries but Meyda looks beautiful.

**Comment by hughrawlinson** [comment]
You could do this, but you'd have to handle a lot yourself. Plus, you wouldn't actually need Meyda, you could just directly use [fftjs](https://www.npmjs.com/package/fftjs). Meyda certainly doesn't have tooling to output the DTMF values directly.

But, using fftjs, you could do it like this:

1. Get your audio input in whatever format into list of Javascript numbers however you need to - [here](https://www.hughrawlinson.me/posts/2021/05/19/loading-audio-in-node-js) is how I recommend loading audio in NodeJS for example. I'm not sure what a Wegstreke is.
2. Run your audio through fftjs to get the frequency domain. You'll need to do so at reasonably high buffer sizes, certainly at least 4096 samples long to get the right resolution.
3. For each fft result, check for activation in each of the frequencies per [the DTMF spec](https://www.itu.int/rec/T-REC-Q.23-198811-I/en), and if those frequencies are active, look up the corresponding symbol from a table.
4. You might also need to implement debouncing so that you don't trigger the same symbol repeatedly while it's pressed.

Hope that helps!
