### ISSUE TITLE
Node 18 support

### ISSUE THREAD

**Issue by remlse** [meyda/meyda#1470]
Hi! I see that node 18 is not suported in `package.json`. Is this a concious decision, maybe some breaking change that needs fixing?

Or could this just be added and probably work fine?

**Comment by hughrawlinson** [comment]
Probably the latter. We didn't add it because at the time node 18 wasn't out, and we don't want to commit to supporting versions of node with breaking changes before we run the test suite. Just need to open a PR adding it there, and to the test matrix in the build config. I'll get around to it as soon as I have time - or I'd be happy to review a PR from you if you like. Make sure to follow the [commit message conventions](https://www.conventionalcommits.org/en/v1.0.0/) though!

**Comment by remlse** [comment]
Thank you for the response! I've opened a PR with the suggested changes.
