### ISSUE TITLE
Add better docs and API reference

### ISSUE THREAD

**Issue by lazarljubenovic** [meyda/meyda#201]
I've checked the wiki, read some issues, looked at tests and the source, skimmed the paper, but I still have no idea how to use the **offline extracting** mode. Please note that I'm clueless about music in general and about audio-processing, so nothing is "obvious" or "simple" to me. Trying to catch up with some basics by Googling around.

The wiki mentions `Meyda.extract(feature, signal)` and it seems straight-forward to use, but `signal` is supposed to be a buffer. I understand the point of using buffers for real-time analysis where audio data is a stream, but here are some questions a beginner like me has:

- Why do I have to do the same with "offline" extraction? Why can't I simply give it the whole channel data? Why buffers?
- Real-time `options` expects a windowing function name, does this mean I have to do the windowing-thing myself before I pass it through the extraction method?

#### Attempt 1
```es6
export const extractMfcc = source => {
  const channelData = source.buffer.getChannelData(0)
  return Meyda.extract('mfcc', channelData) // ERROR: not power of two
}
```

#### Attempt 2
```es6
export const extractMfcc = source => {
  const channelData = source.buffer.getChannelData(0)
  const results = []
  // do I have to do this myself? if so, why doesn't the lib handle it?
  for (let i = 0; i < channelData.length - 512; i += 512) {
    const r = Meyda.extract('mfcc', channelData.slice(i, i + 512))
    results.push(r)
  }
  return results
}
```

I understad that the idea of this lib might be a helper library for people who already have a solid knowledge of the matter, but it would be great if newcomers like me who are interested in the subject could learn new stuff, too.

Providing the documentation is never an easy job, and I'd gladly help with proofreading, giving feedback about how understandable it is to a beginner, etc.

---

Here's what an "ideal" documentation looks like for me. It's not something we can (or should) add in one go, but we can build towards it, bit by bit.

# Docs

Almost in a form of tutorials, they try to cover as much as possible, going step by step, explaining rationale behind each decision, exploring/mentioning/encouraging alternative ways to do the same thing, and explaining some key concepts about audio processing in general. Full of _small_, _isolated_ but _complete_and _self-contained_ examples.

# API Reference

Assumes the reader already has solid knowledege of the lib and audio processing, and is referring the API just to check some technical details: default parameters, their order, format, measurement units, implementation details that affect the result. Also provides external wiki/papes links to read more about the mathematical model of the feature.

**Comment by hughrawlinson** [comment]
@lazarljubenovic thanks for this issue! You're totally right, we'd love to have better documentation. The more specific issues and questions we get, the better we're able to make things clear for everyone.

> Why do I have to do the same with "offline" extraction? Why can't I simply give it the whole channel data? Why buffers?

Can you explain what you mean by 'the whole channel data'? Where are you getting your audio from? Please post code snippets if possible.

I think you might benefit from a wrapper library - if I understand you correctly, you want the average MFCC values across a longer sample of audio (i.e. greater than say 1024 or 2048 samples in length). The reason the buffer length has to be a power of two is because of how the underlying FFT is implemented (if I understand correctly @nevosegal?). There's a technique called zero-padding to let you take a buffer of any length, and pad it out on either side with 0s until it's length is the next greater power of two. Usually this is applied after windowing though, so we really ought to do this inside Meyda, rather than in a wrapper library on top. In the mean time, you could do something like this:

```
export const extractMfcc = source => {
  const channelData = source.buffer.getChannelData(0)
  // apply windowing function
  const buffer = Meyda.windowing(signalToBeWindowed, "hanning")
  // get half the difference between the current length of the channelData and the next power of two
  const halfPaddingLength = Math.pow(2,Math.floor(Math.log2(buffer.length)) + 1) - buffer.length
  // create an array full of zeroes for the half pad
  const pad = new Array(halfPaddingLength).fill(0);
  // put the half length pad on each side of the channelData, making the full pad
  return Meyda.extract('mfcc', [...pad, ...channelData, ...pad])
}
```

---

Aside: this function will take quite a long time if your source file is large. For various reasons (such as [fine control over step size and overlap](https://cas.web.cern.ch/cas/Denmark-2010/Caspers/Tektronix%20%20primer%20on%20overlapping%20FFT%20signals%202009%20CAS2010.pdf)), you may prefer to chunk your input, possibly with even varying step size and overlap, and take some kind of weighted average of your features. Hard to know for sure without knowing your use case.

---

> Real-time options expects a windowing function name, does this mean I have to do the windowing-thing myself before I pass it through the extraction method?

Meyda does windowing internally, the windowing function name lets you select which of the windowing functions we've implemented to use. The list of windowing functions we've implemented is available [here](https://github.com/hughrawlinson/meyda/wiki/audio-features#windowing-functions).

---

As for examples - I'd *love* to provide some examples of Meyda working. At the moment, I think the best we have is the cli in this repo, and our [showcase site](https://hughrawlinson.github.io/meyda/), in the gh-pages branch of this repo. If you write code using meyda we'd love to point to it as an example!

Explaining how low level signal processing works to beginners seems like a pretty difficult task to me, because so much of it just seems like crazy math magic. Still worth making an effort, and doing our best. I like your way of splitting out docs and a reference, so I'll take a stab at it. I'll also have a look at writing a document that explains how to apply windowing, zero-padding, and overlapping frames in meyda.

Another thing that might be good is using error messages to point to explanations in our docs - i.e. `not a power of two` should point to a section in docs and explain that the fft algorithm requires that its input be of a length that is a power of two, explain why, explain how to pad input (and link out to resources explaining how windowing and padding work), and then provide a method that just does it.

**Comment by hughrawlinson** [comment]
Update: I made [a jsbin](https://jsbin.com/fecodo/edit?js,console) that shows what I said above doesn't work.

I'm working on another, bear with me, it'll be tomorrow before I'm finished 😄

**Comment by nevosegal** [comment]
Just to take on what @hughrawlinson mentioned about the power of two issue. Yes, our FFT implementation (like many others) is based on a radix-2 [Cooley-Tukey ](https://en.wikipedia.org/wiki/Cooley%E2%80%93Tukey_FFT_algorithm) algorithm. The radix-2 stands for recursively dividing the the time-domain input into two equal chunks, until we are left with inputs of length 2. This is only possible when the input is a power of two unfortunately. As mentioned, one way to overcome this is to zero-pad the input (no need to zero-pad on both sides, appending/prepending is enough), and I agree that Meyda should do it internally, especially for the offline extraction. The web-audio API already provides the input as a power of two.

**Comment by lazarljubenovic** [comment]
@hughrawlinson 

> Can you explain what you mean by 'the whole channel data'? Where are you getting your audio from? 

I'm trying to implement basic speech recognition app with MFCC and DTW. Basically, there should be a few (10) pre-recorded samples. They're all under a second long (average is around 600ms). The user is prompted to record a word, and the systems should calculate the best match. 

[Here's relevant stuff that I have for now.](http://jsbin.com/qocera/6/edit?js,console)

My first idea was to run it live against user's input from mic and keep matching all the time but I realized that would be 1) expensive and 2) I have no idea how to do word boundaries or anything like that :sweat_smile: So I'll just let the user press "play", say a word, "pause", and basically create a sound file from that period (I'm working on this at the moment), extract MFCC, run DTW between recorded utterance and samples, and highlight the closest word (or nothing if below some threshold).

The values I get locally with my chunking "by hand" are the same as values I get when I connect the data to the source, play it, and run the "live" feature extraction with MeydaAnalyzer, so I guess that I'm doing it right. Which also means, if I'm understanding it correctly, that Meyda doesn't do any overlapping when extracting features live? Seems like WAAPI doesn't really give anything out of the box for this, right? 

Does :arrow_up: sound like a plan? It's a project for university; we have Information Retrieval subject, but all we did in classes was text. So I decided to try our MIR for the project, and now for a few days I'm on a roller-coaster of "this is awesome" - "I'll never finish this" - "omg this actually works" - "crap it doesn't". :smile: But at least I'm having a lot of fun :tada:

As for the examples, I'll have to write a report on this project anyway, so hopefully it will be a nice contribution to have an app, _and_ a complete overview/tutorial/explanation of how it works (as much as I can understand at least). Rest assured that I'll throw a link here once I'm done. I just hope that ~magic~ maths behind the filters won't let me down and that it will actually work at least 80% of time, given that the samples are a small set of words which are pretty distinct from one another.

PS. WAAPI has `createAnalyser` and Meyda has `createMeydaAnalyzer` (s/z). Ah, English language. Fun, fun, fun. :man_facepalming:

**Comment by hughrawlinson** [comment]
Hey @lazarljubenovic - we've just pushed a big update to our documentation - it's available [here](https://meyda.js.org/). Thanks for pushing us to improve! We'd really appreciate if you took a look at it and let us know if anything is still unclear.

**Comment by lazarljubenovic** [comment]
As it usually goes with lazy students like me, I've finished the university assignment and completely forgot about everything :sweat_smile: I'll check it out during the week -- gonna refresh my memory too! :sparkles:
