### ISSUE TITLE
Impossible to install meyda 4.1.x

### ISSUE THREAD

**Issue by hugohil** [meyda/meyda#225]
Hello,

I tried to install the latest versions of meyda (`4.1.0`,  `4.1.1` and `4.1.2`) but I get a `Cannot find module 'meyda'` error.
When I take a look inside the installed `node_modules/meyda`, I see it has no `dist/` folder, so I guess its a build/deploy issue.

`4.0.5` works fine though.

Cheers :)

**Comment by jakubfiala** [comment]
@hugohil thanks for flagging this up, it is indeed a known deployment issue and we should have fixed it a while ago, we were all a bit too busy. I'll see if I can look at it today, it seems it's something to do with the way npm handles `.npmignore` since npm v5

**Comment by hugohil** [comment]
Great :) I'll let you close the issue then

**Comment by jakubfiala** [comment]
@hugohil this should now be fixed and published as `4.1.3` 🎉

The issue was that the 'empty npmignore' trick didn't work, i.e. npm was falling back to gitignore when publishing, but not when running `npm pack`. We obviously want to gitignore `/dist` but we don't want to npmignore it, so I had to add `!dist` to npmignore, which fixed the issue.

Sorry about this period of inconvenience and hope you all enjoy the new features!

**Comment by odub** [comment]
Huge appreciation @jakubfiala

**Comment by nevosegal** [comment]
Thanks @jakubfiala

**Comment by hughrawlinson** [comment]
Great stuff @jakubfiala, thanks so much for sorting it, sorry I wasn't sufficiently available to help!
