### ISSUE TITLE
Updates to getting started documentation

### ISSUE THREAD

**Issue by RichardJECooke** [meyda/meyda#235]
Trying this library for the first time using https://github.com/meyda/meyda/wiki/Getting-Started.

It's a bit confusing. You give the code upside down so I tried to put it in order like this:

```
let meyda = require('meyda');

let context = new AudioContext();
let song = new Audio('media/song.mp3');
let source = context.createMediaElementSource(song);
let options =
{
	"audioContext": context, // required
	"source": source, // required
	"bufferSize": 512, // required
	"hopSize": 256, // optional
	"windowingFunction": "hamming", // optional
	"featureExtractors": ["rms"], // optional - A string, or an array of strings containing the names of features you wish to extract.
	"callback": getFeature // optional callback in which to receive the features for each buffer
};
let analyser = meyda.createMeydaAnalyzer(options);

analyser.start(features);

function getFeature(features)
{
	text = JSON.stringify(features, null, 4);
	console.log(text);
}
```

1. Where do I find AudioContext and Audio?  They aren't defined
2. What type of function is start? Is it a promise (hopefully)? If not, then how does stop work?

Thanks!

**Comment by hughrawlinson** [comment]
Hi @RichardJECooke!

I agree, this is a bit confusing.

1. [AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) and [Audio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) are part of the browser's inbuilt APIs. `AudioContext` is part of the Web Audio API, and `Audio` is the constructor for a new HTML5 audio element. We should clarify in the guide that this guide is focussed on javascript executing in a browser. While there are some implementations of these APIs for Node.js, this guide isn't exactly appropriate for that use case. We'll look into writing a tutorial for node.js.

2. the `start` function isn't a promise, it sets state inside the meyda object to tell it to start listening to the source node and returning the features to the `callback` method provided in `options`. This library was designed mostly before promises were big, so the API doesn't use them. If we were rewriting it today, we'd probably have the `start` function return a promise that contains an iterator. Perhaps I'll write an updated interface to Meyda at some point.

Hope that helps! Feel free to ask any other questions you have and I'll be happy to answer them.

Best,

Hugh

**Comment by RichardJECooke** [comment]
Ohhh, thanks. I see now the node web-audio-api is both incomplete and abandoned.  I'll try the browser instead. 

Do you have any basic sample code to show this library works though?  Just like opening a file and displaying the mp3's features?  That's really what should be in the 'getting started' page. Otherwise we're all just fiddling in the dark trying to use this thing.

I see there's a demo linked from the docs, but its source code just imports meyda and threejs. I can't see anywhere how the page actually runs :(

**Comment by hughrawlinson** [comment]
[Here's the demo running](https://meyda.js.org/), and the source for the demo is available [here](https://github.com/meyda/meyda/tree/gh-pages). I'll look at updating the link. Thanks for the feedback! 😄

**Comment by RichardJECooke** [comment]
Thanks. I got my code in the previous comment extracted from your `getting started` page to build and run.

(I had to change `analyser.start(features)` to `analyser.start()` because `features` is mentioned in the docs but never defined. Did you mean `options`? You define that. Or is my way correct?)

But anyway it returns an rms of 0 whether or not the track is playing:
![untitled](https://user-images.githubusercontent.com/5468805/44036370-eaa35932-9f11-11e8-88b9-3ab8841cb14e.png)

I don't understand how your demo code works at all, it's nothing like the docs. You use
```
    this.meyda = Meyda.createMeydaAnalyzer({
      audioContext: this.context,
      source: stream,
      bufferSize: bufferSize,
      windowingFunction: 'blackman'
});
```
Where is your start function? And your callback function to render?

Can you see why my code returns only 0 please?  And why it runs continuously even when the song isn't playing or has finished?

**Comment by hughrawlinson** [comment]
Hi Richard,

I agree this should be much clearer. I'll clarify things here and go back to the docs to update them.

> (I had to change analyser.start(features) to analyser.start() because features is mentioned in the docs but never defined. Did you mean options? You define that. Or is my way correct?)

`start` accepts an argument called `features` that can override the `features` defined in `options`. `features` should be a list of the audio features that you want Meyda to extract, for example `var features = ['rms', 'spectralCentroid'];`. It's so that you can stop and start extraction with different feature sets without having to re-instantiate a new Meyda. See [this line of the source](https://github.com/meyda/meyda/blob/master/src/meyda-wa.js#L90).

> Where is your start function? And your callback function to render?

Meyda provides a couple of ways to get the audio features out of it. One way is that the options object can contain a callback that will be called with audio features for each frame of audio. This is useful when you need the audio features at every single frame of audio. Another way is the `get` function, which can be called at any time to get the most recent set of audio features. This is useful when you don't need audio features for every single frame of audio, but need them on demand. In the case of our demo, because the frame rate of the visualization is much slower than the audio frame rate, we don't need to calculate the audio features for every single frame - just when it's required for a new frame of the visualization. Inside the `requestAnimationFrame` callback, you'll see that [we call Meyda's `get` function](https://github.com/meyda/meyda/blob/gh-pages/src/main.js#L113). That's how the demo works.

As for why your code returns 0s, I'm not sure right now. I'll try running the code and seeing what's happening. Do you have your code in a repo somewhere? I'm interested in seeing what you're working on 😄

**Comment by RichardJECooke** [comment]
Thanks, I'll take a look at these ideas.
My code is here: https://bitbucket.org/rjeapps/graphic_score_maker/src/master/, I'm basically trying to create graphic scores from songs. 

So eventually Meyda -> numbers -> drawing library -> .bmp.

**Comment by 2xAA** [comment]
Hey @RichardJECooke - here's a JSBin based off of your code in the OP.

https://jsbin.com/nanobiw/edit?js,output

Hope this helps you out 😄

**Comment by RichardJECooke** [comment]
Just wanted to say thanks to @hughrawlinson and @2xAA for your help with this.
I finished my prototype for an automated graphic score generator, thought you might be interested to see: http://graphicscore.richardcooke.info/

I realise now that it's an impossible idea. Wave analysis just can't do what a human can do yet.

**Comment by hughrawlinson** [comment]
@RichardJECooke happy to help!

> it's an impossible idea

That sounds like a fun challenge to me 😄 Maybe you could explain more about what you were hoping to achieve, and share some hand drawings, and we could point you in the right direction? It's quite possible that Meyda just doesn't support what you need at the moment, but it's also quite possible that we can identify what you might need and implement it. I'm reasonably confident that the signal processing community has identified audio features that would be more useful to you.

**Comment by hughrawlinson** [comment]
Hey, thanks so much for the feedback @RichardJECooke! We've worked hard to improve the docs recently, and would really appreciate feedback if you have any. [Here's the link](https://meyda.js.org/getting-started) to the new Getting Started documentation.

**Comment by RichardJECooke** [comment]
Wow, those docs look fantastic! Well done.  That'll definitely help new users.

I think now I'm going to try use the WebAudio analyser directly and see how that works. People can do amazing stuff with just that, like creating music videos in three.js: http://www.dennis.video/#
