### ISSUE TITLE
NodeJS Implementation - Incorrect Results

### ISSUE THREAD

**Issue by derekpankaew** [meyda/meyda#269]
Hi All,

I'm trying to get Meyda to work in NodeJS, without a web client. My approach is to take a buffer of audio, input it into Meyda, console log the result, then repeat with the next buffer.

Unfortunately, it's giving me results that don't make sense. For example, I deliberately created a .wav file that goes quiet-medium-loud. 

The results in NodeJS for RMS have no correlation to volume at all. In other words, the result seems completely random. In command line however, it works just fine.

In NodeJS, I get the result below. There's no correlation at all to the actual volume, it just bounces up and down:

```
105.1019931228357
104.80695618528912
99.46759250921755
106.39200948686154
106.81654981669173
105.43344143021493
106.01526096676248
105.74412954120615
101.77046505848905
100.43762479558181
98.4534535997759
101.3409928035522
101.71081086332381
99.93928288356072
102.5985285949796
101.00187766476262
105.18379123591727
101.68481861981412
99.27941672804646
100.1511545906427
99.97191565906343
98.97534141777412
101.01919694530346
100.87247924693582
100.50801890789575
100.89600737589971
101.09426351715982
101.2877258400813
100.87780336917167
100.88044755132412
100.65454800585603
100.83133685725338
101.1316827642153
100.39256436901069
100.79375441577726
93.45614434371917
99.76712114573039
95.74791004469083
99.90719206371524
99.847085243522
101.27474210882409
94.87187014614422
94.73986616147148
```

But in command line, the numbers go from low to high, which is correct:

```
0.0003836418798428889
0.00041570994459162237
0.00036482210196996795
0.006694272447839924
0.0003898980687894166
0.005106579655434546
0.006404633018223204
0.0030779943053732242
0.0041607191963832675
0.008586127732167922
0.007282952379380984
0.006258594377839065
0.006869457289293675
0.007498690564016819
0.006366275595409506
0.009295227510706165
0.008841116585079698
0.0456591595236661
0.013050169064247557
0.04562089371547452
0.015438806133475208
0.027398288664481886
0.037313695584666275
0.035024847152729896
0.009520691078186498
0.03108087825435302
0.031905312591557995
0.030946609346253418
0.0382024009109569
0.15642666019396356
0.13780744795519992
```

I'm wondering what I'm doing wrong, and how I can get the implementation to work in Node.

Here's my code below. Any thoughts would be much appreciated:

```
const Meyda = require('meyda');
const fs = require('fs');

const bufferSize = 16384;

var buffer = fs.readFileSync("./test2/volumetest.wav")

// Calculate number of times a full buffer can be filled

var numberOfBuffers = buffer.length / bufferSize; 

// Create a loop, which feeds each buffer of 16384 bytes into Meyda

for (var i = 0; i < numberOfBuffers - 1; i++) {

    // Take the full buffer, and extract one segment of 16384 bytes
    
    var currentBuffer = buffer.slice(i*bufferSize, (i + 1) * bufferSize);  
    
    // Use Meyda on the current buffer
    
    var result = Meyda.extract('rms', currentBuffer);
    
    // Output the result
    
    console.log(JSON.stringify(result, undefined, 2));
    
}
```

**Comment by jakubfiala** [comment]
Hi @derekpankaew – from your code it looks like you're loading the entire WAV file using `readFileSync` and then passing the raw binary data to Meyda. This doesn't work, because `Meyda.extract` operates on buffers of *samples*, rather than raw WAV data – in fact I'm surprised your code didn't throw an error (it probably should, CC @meyda/owners).

A WAV file is slightly more complex than just a list of sample values – it has a header defining how the samples are represented, and the samples can be in many formats. For instance, you could have a WAV file where each sample is a 8bit integer, or a 16bit little-endian integer, or a 32bit floating point number. So in order to extract the sample values in a format that Meyda understands (which is 32bit floating point), you need to parse the WAV file in some way.

For the command line Meyda program, we've written a [`WavLoader`](https://github.com/meyda/meyda/blob/master/bin/wav-loader.js) utility, which uses the `wav` library to parse a file and streams the parsed samples in chunks. [Here's](https://github.com/meyda/meyda/blob/master/bin/cli.js) the code for the CLI itself. 
That's why your RMS values were correct in the CLI, and incorrect in Node.

Hope that helps, feel free to reuse our WAV loader code and ask further questions :) I'm going to close this issue now, but happy to keep the discussion going.
