### ISSUE TITLE
Meyda.extract should throw if `signal` isn't a Float32Array

### ISSUE THREAD

**Issue by jakubfiala** [meyda/meyda#270]
This arose from #269 – currently we're checking if `typeof signal === 'object'`, which could include any object, including a node `Buffer`. It would prevent future confusion if the `extract` method threw when passed an object such that `signal instanceof Float32Array`.

Personally I'd restrict it to F32A as I don't see any value in accepting `Array` – but I might be wrong of course :)

**Comment by hughrawlinson** [comment]
I can see good reasons for it to not be a Float32Array - perhaps your audio is stored on disk as unsigned 16 bit ints. If Meyda didn't accept those, you'd have to map the signal to F32, which could be an expensive operation. (Relatedly, if we haven't already, we should check how Meyda handles signals that are all above zero, rather than what I had always assumed, that they're centred on 0+dc-offset.)

If Meyda did the conversion, we wouldn't be able to do a full pass of the signal before iterating through, so we'd end up mapping the same samples multiple times for some extraction configurations where step size is less than buffer size, so I don't think Meyda should do an internal conversion.

For that particular problem though, we could do more validation on the input signal - that it's an iterable that consists only of numbers. `typeof signal === 'object'` isn't good enough. Have you worked with Typescript or Flow at all? Maybe we could look into that and see if type annotations would be useful.

**Comment by jakubfiala** [comment]
@hughrawlinson I get what you mean, but `Number`s in JS are 32 bit floats anyway – and at the moment many of the extractors will actually pull out values from your signal into `Number`s and/or F32Arrays. Take [energy](https://github.com/meyda/meyda/blob/master/src/extractors/energy.js), for example – we're accumulating a value into a standard JS variable, so the samples are in fact converted to float32 by the extractor itself.

Personally I'd be in favour of at least limiting it to TypedArrays, standard Arrays are just too flexible and can contain practically anything – but it's def up for discussion.

Using TS or Flow might be a good idea anyway – how does it work for non-TS/Flow projects though? When we compile and minify the library, will it still do the typechecking internally?

**Comment by hughrawlinson** [comment]
I've actually been working on Typescript for Meyda, and I think we can resolve this in that PR - either way, I'd prefer a compile time type error to a runtime thrown error.
