### ISSUE TITLE
Change the number of Sample Rate however the number of Meyda feature output did not change

### ISSUE THREAD

**Issue by Nhatmusic** [meyda/meyda#284]
Hi, It's said that "You can calculate how many sets of audio features Meyda will output per second by dividing the buffer size by the sample rate". However, When I keep the same buffer size but change the number of sample Rate, the number of output feature does not change. It always keeps the (44100/bufferSize)=number of feature. 
Could you please consider explaining the problem? and Is there any way to configure the Analyzer so that for every different audio(different length in second), we can get the same number of output features? 
Thank you so much.

**Comment by hughrawlinson** [comment]
Hi!

Meyda works by chunking incoming audio into buffers, each of length `bufferSize`. It then extracts audio features from each buffer and returns them. If your buffer size is 512, and your sample rate is 44100, you would have 86.132 buffers per second. Meyda will return the audio features for each buffer it receives when you register a callback. If you want to decrease the number of buffers per second, you could choose a higher buffer size. For example, a buffer size of 2048 will yield 21.533 buffers per second.

Choosing a buffer size is extremely important - for example, if you need to do an audio visualisation that runs at 60fps, you will need at least 60 audio buffers per second. Therefore, you would choose 512 as your buffer size. Buffer sizes must be powers of two, to make some of the underlying math work. If you were to choose the next power of two, 1024, you would only get 43.066 buffers per second, which would lead to jittery graphics.

If you need more detailed audio features, you should choose a higher buffer size - the buffer size dictates the resolution of the underlying fast fourier transform, and hence the resolution of the audio features.

In your case, it sounds like you're trying to compare the audio features of audio clips of different lengths. The best way to do this can vary wildly depending on your application. For example, if you just care about the envelope of the features as a percentage of the length of each audio clip, you might take audio features at the same rate across all your audio clips, and then resample your audio features so that you end up with the same number of features per clip regardless of length. In that case, I'd encourage you to overlap your buffers though, and take high resolution audio features so that your resampling would be successful.

A simpler approach is to take the audio features of all your audio clips at the same rate regardless of the clip length, and then average the results for each clip. The average audio features can be a reasonable representation of a clip for many purposes.

I hope that helps! Let us know if you have any more questions.

**Comment by Nhatmusic** [comment]
Thank you so much for the answer in detail. It helps me a lot.
