### ISSUE TITLE
Change Sample Rate value when calculating MFCC, it does not change how many times it calculates the level in one second

### ISSUE THREAD

**Issue by Nhatmusic** [meyda/meyda#393]
As mention in your documentation about real-time audio example, 
"Usually there are 44100 Audio Samples in 1 second, which means in this case Meyda will calculate the level about 86 (44100/512) times per second."

The feature that I calculate is mfcc. buffer size: 512. I expected that when I change the sample rate to 22050, it will calculate the feature about (22050/512) = 43 times per second. However, it does not matter how I change the sample rate value, the number of returned feature in one second never change.

**Comment by hughrawlinson** [comment]
The sample rate parameter on Meyda doesn't make Meyda resample audio. It's more like a hint, to tell Meyda what the sample rate of the audio it receives is. If you set the sample rate to 22050, but provide an AudioNode from a 44100 rate AudioContext, Meyda will still output the same number of features per second, and they will be calculated incorrectly because Meyda will have incorrect information about the sample rate. If you set the sample rate to 22050 on Meyda, you have to also make sure to provide it only 22050 samples per second.

If you're sure you're providing only 22050 samples per second but Meyda is returning 86 features per second, it would be great if you could provide us with a reproduction of the issue on something like [this](https://observablehq.com/).

**Comment by Nhatmusic** [comment]
Thank you so much for your response. It helps me a lot. Now, I understand that I have to control the sample rate from AudioContext rather than using Meyda sample rate config. It works.

**Comment by hughrawlinson** [comment]
Happy I could help!
