### ISSUE TITLE
_melToFreq and _freqToMel wrong constant ?

### ISSUE THREAD

**Issue by damienlaine** [meyda/meyda#458]
Greetings,

Seems like these MFCC extraction utilities functions relies a constant which is set to 1125 in Meyda's implementation. I observed slight diferences between Meyda's and expected test results on some MFCC extraction.

O'Shaughnessy's mel-scale formula, which is widely used everywhere, uses this "1127" constant. 

Maybe Meyda would benefit from this de-facto standard constant ?
Maybe there's another explanation for this choice (Javascript rounding ?)

I would like to know community's insights on this.

Many thanks,

**Comment by hughrawlinson** [comment]
Hi! @nevosegal any insights here?

**Comment by nevosegal** [comment]
Hi @damienlaine, that's a good point. Although there is no "correct" number, from a quick search it looks like 1127 is the most widely used.

Are you up for fixing it and opening an MR?

**Comment by damienlaine** [comment]
Sure, but i'm quite confused about your contribution guidelines. `Always work on the ‘next version branch’, whose name is the version number of the next release.`
This is quite cryptic as there's no such branch. Any clue ?

**Comment by hughrawlinson** [comment]
Looks like I need to update our contribution guidelines, sorry! The only constraint you need to follow is to make sure your commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary). In this case, this would be a breaking change, since it'll change the output of the mfcc feature extractor between versions. If you make your commit locally, the tooling should lint your commit message and let you know if it doesn't match.
