### ISSUE TITLE
Slight offset in amount of frames calculated per second

### ISSUE THREAD

**Issue by DavidLifshitzSmit** [meyda/meyda#868]
Hi!

So I just started using Meyda since yesterday (So far great to see this on javascript, as I'm used to Librosa on Python). 
I'm interested to run it live on a web browser, calculate MFCCs for each second and then define classify it based on the data I have. So, according to the Meya documentation, the sample rate is 44100 samples/second. Whenever choosing a buffer of 512 samples, I would expect to acquire 44100/512 = 86 frames per second. However, I'm acquiring ~93 frames per second, each existing of indeed 512 samples. This makes me feel that sample rate is more like 93*512 = 47600.
My code is as follows:

function setupMeydaAnalzer () {
  let audioCtx = createAudioCtx ()

  createMicSrcFrom ( audioCtx )
  .then ( ( src ) => {
      let analyzer = Meyda.createMeydaAnalyzer ({
          'audioContext': audioCtx,
          'source':src,
          'bufferSize': 512,
          'featureExtractors':["mfcc","rms", 'buffer'],
          'callback':callback
      })
      
      analyzer.start ()
  }).catch ( ( err ) => {
      alert ( err )
  })
}

function callback ( features ) {
  let mfcc = features["mfcc"]
  let rms = features["rms"]
  const THRESHOLD_RMS = 0
  const MFCC_HISTORY_MAX_LENGTH = 1000 
  // ----------------
  console.log('Frames per second:', mfcc_history.length / (Times[Times.length - 1] - Times[0]) * 1000 )
  // ----------------

  
  if ( rms > THRESHOLD_RMS ) {
      Times.push(Date.now())
      mfcc_history.push ( mfcc ) 
  }

  if (mfcc_history.length > MFCC_HISTORY_MAX_LENGTH) {
      mfcc_history.splice(0,1) 
      Times.splice(0,1) 
  }
}

Is there something I'm doing wrong? What could I do to actually acquire the amount of frames I expect (86 in this case). 
Im afraid that my training set of 1-second wavs will be different than the 1-second MFCCs/buffers/spectrograms I would expect to get due to this offset.

First time I'm posting an issue on git, so please forgive me if I skipped or missed on some expected formalities!
And then, thanks for the awesome package you build =)

**Comment by hughrawlinson** [comment]
Hi @DavidLifshitzSmit, thanks for using Meyda! Happy to help if you have any questions! You didn't skip any formalities, thanks for sharing your code so we can see what's happening. Meyda doesn't set it's own internal sample rate, it should use the sample rate of whatever audio it receives. It looks to me that since your expected sample rate based on your calculations is 47600, you're probably using an AudioContext that runs at 48000hz. Let me know if this is the case - otherwise there's a bug I'd like to fix. Unless you manually set a sample rate, Meyda will pick the sample rate based on the audio context, so in this case it will have adjusted to 48000. Hope that clarifies things! let me know if you have any issues!

**Comment by DavidLifshitzSmit** [comment]
Yaaap, I got to to the same conclusion yesterday when reading a resembling answer on a different issue, just before closing this issue. Thanks for answering anyways and I hope Meyda+tensorflow will finally give the results I'm looking for! Thanks a lot bud!
