### ISSUE TITLE
Extracting RMS does not yield expected result

### ISSUE THREAD

**Issue by SaltedBlowfish** [meyda/meyda#879]
First off, I love this library. I think it's an amazing addition to the community. Thank you to the maintainers.

The Issue:

When reading the feature docs, `rms` says:

> Time-domain features
RMS
Description: The root mean square of the waveform, that corresponds to its loudness. Corresponds to the ‘Energy’ feature in YAAFE, adapted from Loy’s Musimathics [1].
    What Is It Used For: Getting a rough idea about the loudness of a signal.
    Range: 0.0 - 1.0 where 0.0 is not loud and 1.0 is very loud.

Here's where the questions / concerns begin:

1. A range of `0.0 - 1.0` doesn't make much sense. RMS isn't a scalar value, so where does this clamp originate? What is it relative to if it's being scaled?
1. When using this feature, the extracted number for this array: `const arr = [3, 2, 3, -1, 0, 1, 3, 6, 2, -2, -5, -11, -1, 2, 8, 11]` is `2.5250930131288265` but a simple calculation shows a different RMS. (Google Sheets screen shot is pasted below for the sake of illustration) I've checked the RMS source code and it's correct, so the problem must lie elsewhere. (https://github.com/meyda/meyda/blob/master/src/extractors/rms.js)

![image](https://user-images.githubusercontent.com/6200478/122621430-59578f80-d04a-11eb-8d0b-d8f8a6644d6b.png)

If the value of `2.5250930131288265` is correct per the context of this library, then perhaps an explanation of _what_ is happening in addition to the RMS in the time-domain is necessary in the docs. It may be that this function inadvertently takes the RMS of the frequency domain, but I have not confirmed.

Meyda code to reproduce the bug:

```
import Meyda from 'meyda';
Meyda.sampleRate = 50000;

console.log(
  Meyda.extract('rms', [3, 2, 3, -1, 0, 1, 3, 6, 2, -2, -5, -11, -1, 2, 8, 11])
);

// prints 2.5250930131288265
```

Thanks again everyone.

**Comment by hughrawlinson** [comment]
Hi @SaltedBlowfish! Thanks for writing the issue!

The range of rms is incorrectly documented. It shouldn't be bound by 0-1. I'll fix that shortly. Thanks for drawing my attention to it!

While our implementation of rms is meant to match every other implementation, the second issue is an example of expected behaviour in Meyda. This is because the Meyda extract method applies the default windowing function (a hanning window) to the signal before extracting the feature. This significantly reduces the rms of the signal. If you'd like the rms of the pure signal, you can set `Meyda.windowingFunction` to `rect`. [Here](https://runkit.com/raw/meyda-rms) is a demonstration of the behavior.

Hope that helps! I'll leave this issue open until I change the documentation to reflect the range of rms. Let me know if you have any further questions.

**Comment by SaltedBlowfish** [comment]
@hughrawlinson Thank you for clarifying! I understand the windowing but there were some strange side-effects I ran into with the RMS value that led me to think there was more going on. 

I'll see if I can reproduce and I'll make a new issue if I find it again.

**Comment by hughrawlinson** [comment]
Thanks! Please let us know if you find any weird behaviour, we would of course love to fix it and make any improvements we can.
