### ISSUE TITLE
prevent larsen/feeback for webcam microphone

### ISSUE THREAD

**Issue by spleennooname** [meyda/meyda#940]
hello, first of all congratulations for the project, extremely interesting! Is there a best practice/example to use the microphone via webrtc in order to avoid larsen? try to explain myself better:

in a success callback after `mediaDevices.getUserMedia({ audio: true, video:true)` i have

```js
run( stream, callback){
   this.audioContext = new AudioContext()
   this.source = this.audioContext.createMediaStreamSource(stream);
   this.analyzer = Meyda.createMeydaAnalyzer({
            audioContext: this.audioContext,
            source: this.source,
            bufferSize: 1024,
            windowingFunction: "blackman",
            featureExtractors: ["rms", "loudness"],
            callback: features =>{
                callback(features)
            }
        });
   this.analyzer.start();
}
```

not so sure if this is the correct order; any suggestions? thanks!

**Comment by hughrawlinson** [comment]
Hey @spleennooname, thanks!

Yes, that code looks right to me, as long as your `stream` variable refers to the stream in the promise returned from your call to `mediaDevices.getUserMedia`. Is it not working?

Not sure what you mean by larsen - latency? When we benchmarked Meyda 6 years ago or so, we found that all the feature extractors were performant enough to run in realtime in major browsers on desktop and mobile - I would be surprised if that's not the case now but if you've found a case where we're not fast enough, please share a demo along with the specs of the hardware you're using. Meyda shouldn't add any latency to the audio since it doesn't have an output, it's a sink node, and if you need to use the source you should connect it directly to what you're connecting it to. If you mean visual latency, the best practice is to not use a callback set on the options to `Meyda.createMeydaAnalyzer`, and instead use the `MeydaAnalyzer.get` [method](https://meyda.js.org/reference/classes/meyda_wa.MeydaAnalyzer.html#get) inside a [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) callback so that you're only analyzing the *current* audio buffer for each rendered frame of your web application, rather than analyzing every frame and updating less frequently.

something like

```js
... your code ...
this.analyzer = Meyda.createMeydaAnalyzer(...);
... your code ...
function onRequestAnimationFrame() {
  const features = this.analyzer.get();
  renderMyVisualization(features);
  requestAnimationFrame(onRequestAnimationFrame);
}
requestAnimationFrame(onRequestAnimationFrame);
```

Let me know if you have any more questions, or if I didn't answer correctly?

**Comment by spleennooname** [comment]
thanks for the quick and kind reply, first of all! What i want is to drive the visual parameters of this webgl effect shader (https://mosh.surge.sh) with meyda :)

:) By "Larsen" I was referring, relative to the microphone, to a feedback loop/"re-entry" effect; Before instantiating the library I have performed `source.connect(audioContext.destination)` (but maybe it depends more on the physical layout of my audio speakers than on meyda, sorry)

thanks for the code, it's probably what I need because I have a webgl render loop and instead of using that callback it seems more appropriate to use (as you suggest) the get from meyda before the shader draw:)

**Comment by spleennooname** [comment]
ok, I think I've solved it :) the render cycle is now:
` 
const draw = (unifObject = {}) => {
      if (!!this.audioExtractor.analyzer) {
        const features = this.audioExtractor.analyzer.get();
        if (!!features) {
          unifObject.lou = Math.round(invlerp(0., 25, features.loudness.total ) * 1e3) / 1e3;
         }
      }
      //
      for (const unif in unifObject) {
        this.renderer.setValue(unif, unifObject[unif])
      }
      this.renderer.draw(canvas)
    }
 `

**Comment by hughrawlinson** [comment]
> By "Larsen" I was referring, relative to the microphone, to a feedback loop/"re-entry" effect; Before instantiating the library I have performed source.connect(audioContext.destination) (but maybe it depends more on the physical layout of my audio speakers than on meyda, sorry)

Ah I haven't heard that term before, sorry! FWIW, meyda shouldn't output any audio, so if you don't need to connect the source to the destination for your own purposes, you can skip that and it should be fine.

Glad that you got your visualization working! It sounds like your questions are answered now? But feel free to let me know if you need more info and I'll reopen the ticket :)

**Comment by spleennooname** [comment]
yes, I'd say I'm good :) if you want to see meyda already in action check out [http://mosh.surge.sh)](http://mosh.surge.sh). I'll probably do a project on github about it. thanks again!
